name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && npm exec react-router dev"
